---
services:
  postgres:
    container_name: postgres-kt-auth
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: auth_api
      POSTGRES_PASSWORD: mypwd
      POSTGRES_DB: kt_auth_api
    ports:
      - "5432:5432"
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP PORT
      - "8025:8025"  # Web Interface
    restart: always

volumes:
  postgres:
    driver: local
  mailhog:
    driver: local
