---
server:
  port: 8080

spring:
  application:
    name: kt-auth-api
  profiles:
    active: ${PROFILE}
  web:
    locale: en_US
    locale-resolver: fixed

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
